import type { Game } from "./types";

export function formatCount(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(n >= 10_000_000 ? 0 : 2).replace(/\.00$/, "")}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(n >= 10_000 ? 0 : 1).replace(/\.0$/, "")}k`;
  return String(n);
}

export const DEMO_GAMES: Game[] = [
  {
    id: "demo-1",
    creator_id: "demo-creator-1",
    title: "3D Flappy Bird First Person",
    description: "Dodge neon pipes in first-person freefall.",
    prompt: "Make a first person 3D flappy bird with neon pipes",
    thumbnail_url: null,
    play_url: null,
    duration_seconds: 45,
    status: "published",
    view_count: 1_950_000,
    like_count: 129_300,
    comment_count: 3_300,
    save_count: 5_100,
    share_count: 7_500,
    theme: "purple-pipes",
    created_at: new Date().toISOString(),
    creator: {
      id: "demo-creator-1",
      username: "zean",
      display_name: "ZEAN",
      avatar_url: null,
      bio: "Building wild short games",
      level: 12,
      coins: 4200,
      follower_count: 88200,
      following_count: 120,
    },
  },
  {
    id: "demo-2",
    creator_id: "demo-creator-2",
    title: "Gta0.5 (3D City Crime Simulator)",
    description: "Cruise a low-poly city for sixty seconds of chaos.",
    prompt: "Open world mini city crime simulator",
    thumbnail_url: null,
    play_url: null,
    duration_seconds: 60,
    status: "published",
    view_count: 126_200,
    like_count: 8_500,
    comment_count: 4_800,
    save_count: 238,
    share_count: 583,
    theme: "city",
    created_at: new Date().toISOString(),
    creator: {
      id: "demo-creator-2",
      username: "luke",
      display_name: "Luke",
      avatar_url: null,
      bio: null,
      level: 8,
      coins: 1750,
      follower_count: 12400,
      following_count: 88,
    },
  },
  {
    id: "demo-3",
    creator_id: "demo-creator-3",
    title: "Candy Land Rush",
    description: "Sprint through sugar tunnels before the timer melts.",
    prompt: "Pink candy land endless runner",
    thumbnail_url: null,
    play_url: null,
    duration_seconds: 30,
    status: "published",
    view_count: 84_000,
    like_count: 9_200,
    comment_count: 640,
    save_count: 1_100,
    share_count: 420,
    theme: "candy",
    created_at: new Date().toISOString(),
    creator: {
      id: "demo-creator-3",
      username: "skyvibes",
      display_name: "SkyVibes",
      avatar_url: null,
      bio: null,
      level: 5,
      coins: 900,
      follower_count: 2482,
      following_count: 442,
    },
  },
  {
    id: "demo-4",
    creator_id: "demo-creator-4",
    title: "Monster Pet Arena",
    description: "Train your fuzzy monster in a tiny battle arena.",
    prompt: "Cute monster pet battler",
    thumbnail_url: null,
    play_url: null,
    duration_seconds: 40,
    status: "published",
    view_count: 2_400,
    like_count: 64,
    comment_count: 12,
    save_count: 18,
    share_count: 7,
    theme: "monster",
    created_at: new Date().toISOString(),
    creator: {
      id: "demo-creator-4",
      username: "arian",
      display_name: "Arian",
      avatar_url: null,
      bio: null,
      level: 3,
      coins: 350,
      follower_count: 190,
      following_count: 40,
    },
  },
];

export const THEME_STYLES: Record<string, { bg: string; accent: string; label: string }> = {
  "purple-pipes": {
    bg: "radial-gradient(ellipse at 50% 20%, #5b2d91 0%, #1a0b2e 45%, #050508 100%)",
    accent: "#7CFC00",
    label: "TAP TO PLAY",
  },
  city: {
    bg: "linear-gradient(180deg, #4aa3ff 0%, #7ec8ff 35%, #2d5a87 70%, #0d1b2a 100%)",
    accent: "#00E676",
    label: "ENTER CITY",
  },
  candy: {
    bg: "radial-gradient(circle at 30% 20%, #ff9ad5 0%, #ff4fa3 40%, #7a1048 100%)",
    accent: "#FFE566",
    label: "START RUSH",
  },
  monster: {
    bg: "radial-gradient(circle at 60% 30%, #a78bfa 0%, #5b21b6 50%, #1e1b4b 100%)",
    accent: "#67e8f9",
    label: "BATTLE",
  },
  neon: {
    bg: "radial-gradient(ellipse at center, #133 0%, #0a0a0f 70%)",
    accent: "#00FF66",
    label: "PLAY",
  },
};
